### ISSUE TITLE
Cannot open include file: 'longintrepr.h'

### ISSUE THREAD

**Issue by liudonghua123** [SpotlightKid/python-rtmidi#116] opened 2022-11-22 08:17 UTC
I tried to install `mido python-rtmidi`, however I got the following errors.

<details>
<summary>shell logs</summary>

```shell
C:\Users\Liu.D.H>pip install mido python-rtmidi
Collecting mido
  Downloading mido-1.2.10-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 kB 434.6 kB/s eta 0:00:00
Collecting python-rtmidi
  Downloading python-rtmidi-1.4.9.tar.gz (251 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.2/251.2 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: python-rtmidi
  Building wheel for python-rtmidi (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      C:\Users\Liu.D.H\AppData\Local\Temp\pip-install-x1o51856\python-rtmidi_7ca99703f3e44eaeb2251410a1aeecce\setup.py:27: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        JACK1_MIN_VERSION = StrictVersion('0.125.0')
      C:\Users\Liu.D.H\AppData\Local\Temp\pip-install-x1o51856\python-rtmidi_7ca99703f3e44eaeb2251410a1aeecce\setup.py:28: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        JACK2_MIN_VERSION = StrictVersion('1.9.11')
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\rtmidi
      copying rtmidi\midiconstants.py -> build\lib.win-amd64-cpython-311\rtmidi
      copying rtmidi\midiutil.py -> build\lib.win-amd64-cpython-311\rtmidi
      copying rtmidi\version.py -> build\lib.win-amd64-cpython-311\rtmidi
      copying rtmidi\__init__.py -> build\lib.win-amd64-cpython-311\rtmidi
      running egg_info
      writing python_rtmidi.egg-info\PKG-INFO
      writing dependency_links to python_rtmidi.egg-info\dependency_links.txt
      writing top-level names to python_rtmidi.egg-info\top_level.txt
      reading manifest file 'python_rtmidi.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.travis.yml'
      warning: no previously-included files found matching '*.rst.in'
      no previously-included directories found matching 'ci'
      warning: no previously-included files matching '__pycache__' found under directory '*'
      warning: no previously-included files matching '*.py[co]' found under directory '*'
      adding license file 'LICENSE.txt'
      adding license file 'AUTHORS.rst'
      writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
      running build_ext
      building 'rtmidi._rtmidi' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\src
      creating build\temp.win-amd64-cpython-311\Release\src\rtmidi
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D__RTMIDI_SILENCE_WARNINGS__ -D__WINDOWS_MM__ -Isrc\rtmidi -IC:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\include -IC:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsrc\_rtmidi.cpp /Fobuild\temp.win-amd64-cpython-311\Release\src\_rtmidi.obj /EHsc
      _rtmidi.cpp
      src\_rtmidi.cpp(243): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-rtmidi
  Running setup.py clean for python-rtmidi
Failed to build python-rtmidi
Installing collected packages: python-rtmidi, mido
  Running setup.py install for python-rtmidi ... error
  error: subprocess-exited-with-error

  × Running setup.py install for python-rtmidi did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      C:\Users\Liu.D.H\AppData\Local\Temp\pip-install-x1o51856\python-rtmidi_7ca99703f3e44eaeb2251410a1aeecce\setup.py:27: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        JACK1_MIN_VERSION = StrictVersion('0.125.0')
      C:\Users\Liu.D.H\AppData\Local\Temp\pip-install-x1o51856\python-rtmidi_7ca99703f3e44eaeb2251410a1aeecce\setup.py:28: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        JACK2_MIN_VERSION = StrictVersion('1.9.11')
      running install
      C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\rtmidi
      copying rtmidi\midiconstants.py -> build\lib.win-amd64-cpython-311\rtmidi
      copying rtmidi\midiutil.py -> build\lib.win-amd64-cpython-311\rtmidi
      copying rtmidi\version.py -> build\lib.win-amd64-cpython-311\rtmidi
      copying rtmidi\__init__.py -> build\lib.win-amd64-cpython-311\rtmidi
      running egg_info
      writing python_rtmidi.egg-info\PKG-INFO
      writing dependency_links to python_rtmidi.egg-info\dependency_links.txt
      writing top-level names to python_rtmidi.egg-info\top_level.txt
      reading manifest file 'python_rtmidi.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.travis.yml'
      warning: no previously-included files found matching '*.rst.in'
      no previously-included directories found matching 'ci'
      warning: no previously-included files matching '__pycache__' found under directory '*'
      warning: no previously-included files matching '*.py[co]' found under directory '*'
      adding license file 'LICENSE.txt'
      adding license file 'AUTHORS.rst'
      writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
      running build_ext
      building 'rtmidi._rtmidi' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\src
      creating build\temp.win-amd64-cpython-311\Release\src\rtmidi
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D__RTMIDI_SILENCE_WARNINGS__ -D__WINDOWS_MM__ -Isrc\rtmidi -IC:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\include -IC:\Users\Liu.D.H\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tpsrc\_rtmidi.cpp /Fobuild\temp.win-amd64-cpython-311\Release\src\_rtmidi.obj /EHsc
      _rtmidi.cpp
      src\_rtmidi.cpp(243): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> python-rtmidi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

C:\Users\Liu.D.H>
```
</details>

**Comment by SpotlightKid** [comment] 2022-11-22 15:37
It's still a duplicate of #115.

**Closed by SpotlightKid** 2022-11-22 15:37 UTC
Labels: duplicate
