### ISSUE TITLE
SyntaxError when compiling wheel on ARM

### ISSUE THREAD

**Issue by HackXIt** [SpotlightKid/python-rtmidi#72] opened 2020-08-26 15:32 UTC
Hello,

I'm having an issue installing your package:

> Collecting python-rtmidi
>   Using cached python-rtmidi-1.4.3.tar.gz (248 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3HQt0G/python-rtmidi/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3HQt0G/python-rtmidi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tNqbau
>          cwd: /tmp/pip-install-3HQt0G/python-rtmidi/
>     Complete output (6 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-3HQt0G/python-rtmidi/setup.py", line 47
>         print("Detected JACK version %s." % jv, file=sys.stderr)
>                                                     ^
>     SyntaxError: invalid syntax
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I attempted to install this package with `pip install python-rtmidi`

This was done on a raspberry pi zero with the latest buster image.

Please help me out here?

This package is a requirement to this project:
https://github.com/onlaj/Piano-LED-Visualizer

**Comment by SpotlightKid** [comment] 2020-08-26 15:37
Python 2 is not officially supported anymore. Use `pip3 install python-rtmidi` (or `python3 -m pip install python-rtmidi`) instead (of course this will erquire Piano-LED-Visualizer to run under Python 3 too),

I commited a fix so that `setup.py` works with Python 2 again a few days ago, though. I'll make a patch release with this fix.

**Comment by HackXIt** [comment] 2020-08-26 15:40
Sadly I'm not the maintainer of Piano-LED-Visualizer and I'm rather unfortunate that it runs on python 2, as I'm aware that it isn't officially supported anymore.
But I'll make sure to file an issue there too.

**Comment by SpotlightKid** [comment] 2020-08-26 16:12
Duplicate of #70.

**Closed by SpotlightKid** 2020-08-26 16:12 UTC
Labels: duplicate
