### ISSUE TITLE
Version 1.5.0 PyPi incompatible with M1 ARM64 architectures 

### ISSUE THREAD

**Issue by Jasonhead44** [SpotlightKid/python-rtmidi#151] opened 2023-05-31 22:01 UTC
installing version 1.5.0 via pip results in a _rtmidi.cpython-310-darwin.so file that is an incompatible architecture for MacOS M1 devices - (have 'x86_64', need 'arm64').

This error results when attempting to use python-rtmidi version 1.5.0:

"dlopen(~/lib/python3.10/site-packages/rtmidi/_rtmidi.cpython-310-darwin.so, 0x0002): tried: '~/lib/python3.10/site-packages/rtmidi/_rtmidi.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))"

Version 1.4.9 resulted in no errors and worked as expected - replacing the _rtmidi.cpython-310-darwin.so file installed with version 1.5.0 with the one installed with 1.4.9 fixes the issue.

**Comment by SpotlightKid** [comment] 2023-06-01 13:06
Duplicate of #149.

**Closed by SpotlightKid** 2023-06-01 13:06 UTC
Labels: duplicate
