### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by damp11113** [SpotlightKid/python-rtmidi#117] opened 2022-11-24 13:02 UTC
I try to install the python-rtmidi but has error

i use python 3.11

```
Collecting python-rtmidi
  Using cached python-rtmidi-1.4.9.tar.gz (251 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: python-rtmidi
  Building wheel for python-rtmidi (setup.py): started
  Building wheel for python-rtmidi (setup.py): finished with status 'error'
  Running setup.py clean for python-rtmidi
Failed to build python-rtmidi
Installing collected packages: python-rtmidi
  Running setup.py install for python-rtmidi: started
  Running setup.py install for python-rtmidi: finished with status 'error'

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [41 lines of output]
  C:\Users\sansw\AppData\Local\Temp\pip-install-l2w4i9an\python-rtmidi_85349052e1e343f09f318a7f2cd7bdf4\setup.py:27: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    JACK1_MIN_VERSION = StrictVersion('0.125.0')
  C:\Users\sansw\AppData\Local\Temp\pip-install-l2w4i9an\python-rtmidi_85349052e1e343f09f318a7f2cd7bdf4\setup.py:28: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    JACK2_MIN_VERSION = StrictVersion('1.9.11')
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\rtmidi
  copying rtmidi\midiconstants.py -> build\lib.win-amd64-cpython-311\rtmidi
  copying rtmidi\midiutil.py -> build\lib.win-amd64-cpython-311\rtmidi
  copying rtmidi\version.py -> build\lib.win-amd64-cpython-311\rtmidi
  copying rtmidi\__init__.py -> build\lib.win-amd64-cpython-311\rtmidi
  running egg_info
  writing python_rtmidi.egg-info\PKG-INFO
  writing dependency_links to python_rtmidi.egg-info\dependency_links.txt
  writing top-level names to python_rtmidi.egg-info\top_level.txt
  reading manifest file 'python_rtmidi.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.travis.yml'
  warning: no previously-included files found matching '*.rst.in'
  no previously-included directories found matching 'ci'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  adding license file 'LICENSE.txt'
  adding license file 'AUTHORS.rst'
  writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  building 'rtmidi._rtmidi' extension
  creating build\temp.win-amd64-cpython-311
  creating build\temp.win-amd64-cpython-311\Release
  creating build\temp.win-amd64-cpython-311\Release\src
  creating build\temp.win-amd64-cpython-311\Release\src\rtmidi
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D__RTMIDI_SILENCE_WARNINGS__ -D__WINDOWS_MM__ -Isrc\rtmidi -IC:\Users\sansw\AppData\Local\Programs\Python\Python311\include -IC:\Users\sansw\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpsrc\_rtmidi.cpp /Fobuild\temp.win-amd64-cpython-311\Release\src\_rtmidi.obj /EHsc
  _rtmidi.cpp
  src\_rtmidi.cpp(243): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-rtmidi
  error: subprocess-exited-with-error
  
  Running setup.py install for python-rtmidi did not run successfully.
  exit code: 1
  
  [43 lines of output]
  C:\Users\sansw\AppData\Local\Temp\pip-install-l2w4i9an\python-rtmidi_85349052e1e343f09f318a7f2cd7bdf4\setup.py:27: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    JACK1_MIN_VERSION = StrictVersion('0.125.0')
  C:\Users\sansw\AppData\Local\Temp\pip-install-l2w4i9an\python-rtmidi_85349052e1e343f09f318a7f2cd7bdf4\setup.py:28: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    JACK2_MIN_VERSION = StrictVersion('1.9.11')
  running install
  C:\Users\sansw\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\rtmidi
  copying rtmidi\midiconstants.py -> build\lib.win-amd64-cpython-311\rtmidi
  copying rtmidi\midiutil.py -> build\lib.win-amd64-cpython-311\rtmidi
  copying rtmidi\version.py -> build\lib.win-amd64-cpython-311\rtmidi
  copying rtmidi\__init__.py -> build\lib.win-amd64-cpython-311\rtmidi
  running egg_info
  writing python_rtmidi.egg-info\PKG-INFO
  writing dependency_links to python_rtmidi.egg-info\dependency_links.txt
  writing top-level names to python_rtmidi.egg-info\top_level.txt
  reading manifest file 'python_rtmidi.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.travis.yml'
  warning: no previously-included files found matching '*.rst.in'
  no previously-included directories found matching 'ci'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  adding license file 'LICENSE.txt'
  adding license file 'AUTHORS.rst'
  writing manifest file 'python_rtmidi.egg-info\SOURCES.txt'
  warning: build_py: byte-compiling is disabled, skipping.
  
  running build_ext
  building 'rtmidi._rtmidi' extension
  creating build\temp.win-amd64-cpython-311
  creating build\temp.win-amd64-cpython-311\Release
  creating build\temp.win-amd64-cpython-311\Release\src
  creating build\temp.win-amd64-cpython-311\Release\src\rtmidi
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D__RTMIDI_SILENCE_WARNINGS__ -D__WINDOWS_MM__ -Isrc\rtmidi -IC:\Users\sansw\AppData\Local\Programs\Python\Python311\include -IC:\Users\sansw\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" /EHsc /Tpsrc\_rtmidi.cpp /Fobuild\temp.win-amd64-cpython-311\Release\src\_rtmidi.obj /EHsc
  _rtmidi.cpp
  src\_rtmidi.cpp(243): fatal error C1083: Cannot open include file: 'longintrepr.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]
```

**Comment by SpotlightKid** [comment] 2022-11-24 23:53
Duplicate of #115.

**Closed by SpotlightKid** 2022-11-24 23:53 UTC
Labels: duplicate
